server:
  port: 8080
  servlet:
    context-path: /mj
logging:
  level:
    ROOT: info
    com.github.novicezk.midjourney: debug
knife4j:
  enable: true
  openapi:
    title: Midjourney Proxy API文档
    description: 代理 MidJourney 的discord频道，实现api形式调用AI绘图
    concat: imkratos
    url: https://github.com/imkratos/midjourney-proxy
    version: v2.4
    terms-of-service-url: https://github.com/imkratos/midjourney-proxy
    group:
      api:
        group-name: API
        api-rule: package
        api-rule-resources:
          - com.github.imkratos.midjourney.controller